version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lou
      POSTGRES_PASSWORD: lou
      POSTGRES_DB: lou_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080